<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>SeniorProjectCompressionApp.Verification</StartupObject>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Verification.cs" />
    <Compile Include="PerformanceTest.cs" />
    <Compile Include="StreamedFilePerformanceTest.cs" />
    <Compile Include="FullOrchestratorTest.cs" />
    <Compile Include="FolderCompressionTest.cs" />
    <Compile Include="LargeFileTest.cs" />
    <Compile Include="EncryptedFileTest.cs" />
    <Compile Include="EncryptionCompatibilityTest.cs" />
    <Compile Include="LifecycleTest.cs" />
    <Compile Include="KdfBenchmark.cs" />
    <Compile Include="..\Compression\**\*.cs" />
    <Compile Include="..\Models\**\*.cs" />
    <Compile Include="..\IO\**\*.cs" />
    <Compile Include="..\Security\**\*.cs" />
    <Compile Include="..\Services\**\*.cs" />
    <Compile Include="..\Decompression\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Buffers" Version="4.5.1" />
  </ItemGroup>

</Project>
